[workspace]
resolver = "2"
members = [
  "ntex-cors",
  "ntex-files",
  "ntex-identity",
  "ntex-multipart",
  "ntex-session",
]

[patch.crates-io]
ntex = { git = "https://github.com/incapdns/ntex.git", branch = "master" }
